version: '3'
services:
  umn-technology:
    container_name: umn-technology-${APP_VERSION}
    image: ${REGISTRY_URL}/${APP_NAME}:${APP_VERSION}
    restart: unless-stopped
    tty: true
    environment:
        TZ: "Asia/Jakarta"
        DB_DRIVER: ${DB_DRIVER}
        DB_NAME: ${DB_NAME}
        DB_HOST: ${DB_HOST}
        DB_PORT: ${DB_PORT}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
        SSL_MODE: ${SSL_MODE}
        JWT_KEY: ${JWT_KEY}
        E_KEY: ${E_KEY}
    ports:
        - "8088:${APP_PORT}"
    networks:
        - my_network

  postgres_container:
    image: postgres:latest
    environment:
        POSTGRES_DB: ${DB_NAME}
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASS}
    ports:
        - "5432:5432"
    networks:
        - my_network

networks:
  my_network:
    external: true